/** Formal English words used by the tone evaluator's formality heuristic. */
export const FORMAL_WORDS = new Set([
	"therefore",
	"thus",
	"however",
	"nevertheless",
	"furthermore",
	"consequently",
	"accordingly",
	"hence",
	"moreover",
	"notwithstanding",
	"prior",
	"subsequent",
	"sufficient",
	"approximately",
	"commence",
	"terminate",
	"utilize",
	"demonstrate",
	"indicate",
	"constitute",
	"establish",
	"determine",
	"obtain",
	"provide",
	"require",
	"regarding",
	"concerning",
	"pursuant",
	"hereto",
	"therein",
]);

/** Informal English words penalised by the tone evaluator's formality heuristic. */
export const INFORMAL_WORDS = new Set([
	"yeah",
	"nah",
	"cool",
	"awesome",
	"great",
	"hey",
	"hi",
	"hello",
	"guys",
	"folks",
	"totally",
	"super",
	"really",
	"pretty",
	"kinda",
	"sorta",
	"wanna",
	"gonna",
	"gotta",
	"okay",
	"ok",
	"sure",
	"btw",
	"imo",
	"tbh",
	"lots",
	"stuff",
	"things",
	"awesome",
	"amazing",
]);

/** Positive sentiment words used by the tone evaluator's sentiment heuristic. */
export const POSITIVE_WORDS = new Set([
	"good",
	"great",
	"excellent",
	"outstanding",
	"superb",
	"fantastic",
	"wonderful",
	"positive",
	"beneficial",
	"helpful",
	"effective",
	"efficient",
	"reliable",
	"robust",
	"powerful",
	"successful",
	"valuable",
	"useful",
	"pleased",
	"happy",
]);

/** Negative sentiment words used by the tone evaluator's sentiment heuristic. */
export const NEGATIVE_WORDS = new Set([
	"bad",
	"poor",
	"terrible",
	"awful",
	"horrible",
	"negative",
	"harmful",
	"damaging",
	"unhelpful",
	"useless",
	"ineffective",
	"inefficient",
	"unreliable",
	"weak",
	"fragile",
	"failed",
	"failure",
	"problematic",
	"unfortunate",
	"unhappy",
]);
